CREATE TABLE IF NOT EXISTS "produto" (
    "id" SERIAL NOT NULL,
    "nome" VARCHAR(50) NOT NULL,
    "preco" NUMERIC NOT NULL,
    "medida" INTEGER NOT NULL,
    "descricao" VARCHAR(255) NOT NULL,
    "quantidade" INTEGER NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "carrinho" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "quantidade" INTEGER NOT NULL,
    "preco_produtos" NUMERIC NOT NULL,
    "frete" NUMERIC NOT NULL,
    "cep" INTEGER NOT NULL,
    "preco_total" NUMERIC NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "relacionamento_produto_carrinho" (
    "id" SERIAL NOT NULL,
    "id_produto" INTEGER NOT NULL,
    "id_carrinho" INTEGER NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_rel_produto"
        FOREIGN KEY ("id_produto")
        REFERENCES "produto"("id")
        ON DELETE CASCADE,
    CONSTRAINT "fk_rel_carrinho"
        FOREIGN KEY ("id_carrinho")
        REFERENCES "carrinho"("id")
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "acesso" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" VARCHAR(255) NOT NULL,
    "senha" VARCHAR(255) NOT NULL,
    PRIMARY KEY ("id")
);